name: "Automerge"
on:
  pull_request_review:
    types:
      - submitted
  status: {}

jobs:
  automerge:
    name: Auto Merge PR
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - id: automerge
        uses: "pascalgn/automerge-action@v0.16.4"
        env:
          GITHUB_TOKEN: "${{ secrets.CI_TOKEN }}"
          MERGE_LABELS: "automerge"
          MERGE_REMOVE_LABELS: "automerge,autorebase,autosquash"
          MERGE_METHOD: "merge"
          MERGE_METHOD_LABELS: "automerge=merge,autorebase=rebase,autosquash=squash"
          MERGE_METHOD_LABEL_REQUIRED: "true"
          MERGE_DELETE_BRANCH: "true"
          MERGE_COMMIT_MESSAGE: "automatic"
          MERGE_FORKS: "true"
          MERGE_RETRIES: "3"
          MERGE_RETRY_SLEEP: "10000"
          MERGE_REQUIRED_APPROVALS: "1"

      - name: Comment on PR
        if: ${{ steps.automerge.outputs.mergeResult == 'merged' }}
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Pull request \#${{ steps.automerge.outputs.pullRequestNumber }} merged!`
            });
