name: "PR Assigner"
on:
  pull_request:
    types: [opened, ready_for_review]
    paths:
      - "CHANGELOG.md"
      - ".github/release-please-manifest.json"

jobs:
  add-reviews:
    name: auto assign
    runs-on: ubuntu-24.04
    steps:
      - uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          configuration-path: ".github/assign.yml"
