name: "PR labeler"
on:
  pull_request:
    types: [opened, ready_for_review, reopened, synchronize]

jobs:
  labeler:
    name: label

    permissions:
      contents: read
      pull-requests: write

    runs-on: ubuntu-24.04
    steps:
      - uses: actions/labeler@v5
